kafka:
  bootstrapAddress: localhost:9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

anime:
  topic: anime